const createRandomData = length => {
  return new Array(length)
    .fill()
    .map((a, i) => Math.round((Math.random() * (Math.random() * 5000) * 5000) / 5000) + 1000);
};

const createRandomSentimentData = length => {
  return new Array(length)
    .fill()
    .map((a, i) => (Math.random() * (Math.random() * 1.8) * 1.8) / 2.0 - 0.6);
};

export const DataLabels = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'];

export const Data = [
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'All subtopics',
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - All subtopics',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'Privacy',
    subTopicNames: ['Privacy', 'Privacy - negative', 'Privacy - positive'],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - Privacy',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'Efficiency, Reliability, Accuracy',
    subTopicNames: [
      'Efficiency, Reliability, Accuracy',
      'Efficiency, Reliability, Accuracy - negative',
      'Efficiency, Reliability, Accuracy - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - Efficiency, Reliability, Accuracy',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'Legitimacy',
    subTopicNames: [
      'Legitimacy',
      'Legitimacy - positive',
      'Legitimacy - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - Legitimacy',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'Transparency, Accountability',
    subTopicNames: [
      'Transparency, Accountability',
      'Transparency, Accountability - negative',
      'Transparency, Accountability - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - Transparency, Accountability',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Biometric identifiers ',
    topicName: 'Biometric identifiers',
    subTopicName: 'Discrimination',
    subTopicNames: [
      'Discrimination',
      'Discrimination - positive',
      'Discrimination - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Biometric identifiers - Discrimination',
      borderColor: '#3e95cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },

  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'All subtopics',
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - All subtopics',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },

  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'Privacy',
    subTopicNames: ['Privacy', 'Privacy - negative', 'Privacy - positive'],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - Privacy',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'Efficiency, Reliability, Accuracy',
    subTopicNames: [
      'Efficiency, Reliability, Accuracy',
      'Efficiency, Reliability, Accuracy - negative',
      'Efficiency, Reliability, Accuracy - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - Efficiency, Reliability, Accuracy',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'Legitimacy',
    subTopicNames: [
      'Legitimacy',
      'Legitimacy - positive',
      'Legitimacy - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - Legitimacy',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'Transparency, Accountability',
    subTopicNames: [
      'Transparency, Accountability',
      'Transparency, Accountability - negative',
      'Transparency, Accountability - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - Transparency, Accountability',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Predictive policing',
    topicName: 'Predictive policing',
    subTopicName: 'Discrimination',
    subTopicNames: [
      'Discrimination',
      'Discrimination - positive',
      'Discrimination - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Predictive policing - Discrimination',
      borderColor: '#c523cd',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },


  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'All subtopics',
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Privacy',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },

  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'Privacy',
    subTopicNames: ['Privacy', 'Privacy - negative', 'Privacy - positive'],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Privacy',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'Efficiency, Reliability, Accuracy',
    subTopicNames: [
      'Efficiency, Reliability, Accuracy',
      'Efficiency, Reliability, Accuracy - negative',
      'Efficiency, Reliability, Accuracy - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Efficiency, Reliability, Accuracy',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'Legitimacy',
    subTopicNames: [
      'Legitimacy',
      'Legitimacy - positive',
      'Legitimacy - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Legitimacy',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'Transparency, Accountability',
    subTopicNames: [
      'Transparency, Accountability',
      'Transparency, Accountability - negative',
      'Transparency, Accountability - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Transparency, Accountability',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Police Hacking',
    topicName: 'Police Hacking',
    topicNameExtra: 'Police Hacking 2',
    subTopicName: 'Discrimination',
    subTopicNames: [
      'Discrimination',
      'Discrimination - positive',
      'Discrimination - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Police Hacking - Discrimination',
      borderColor: '#55aa11',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },


  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'All subtopics',
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Privacy',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },

  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'Privacy',
    subTopicNames: ['Privacy', 'Privacy - negative', 'Privacy - positive'],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Privacy',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'Efficiency, Reliability, Accuracy',
    subTopicNames: [
      'Efficiency, Reliability, Accuracy',
      'Efficiency, Reliability, Accuracy - negative',
      'Efficiency, Reliability, Accuracy - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Efficiency, Reliability, Accuracy',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'Legitimacy',
    subTopicNames: [
      'Legitimacy',
      'Legitimacy - positive',
      'Legitimacy - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Legitimacy',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'Transparency, Accountability',
    subTopicNames: [
      'Transparency, Accountability',
      'Transparency, Accountability - negative',
      'Transparency, Accountability - positive',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Transparency, Accountability',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },
  {
    title: 'Decision making in justice management',
    topicName: 'Decision making in justice management',
    subTopicName: 'Discrimination',
    subTopicNames: [
      'Discrimination',
      'Discrimination - positive',
      'Discrimination - negative',
    ],
    description: `...missing desription...`,
    dataSet: {
      data: createRandomData(DataLabels.length),
      dataSentiment: createRandomSentimentData(DataLabels.length),
      labels: DataLabels,
      label: 'Decision making in justice management - Discrimination',
      borderColor: '#992223',
      fill: false,
    },
    randomCount: createRandomData(DataLabels.length)[0],
  },


];
